import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


ame = pd.read_table('E:/OMI/GRAPH_data/p-am.txt')
eu = pd.read_table('E:/OMI/GRAPH_data/p-e.txt')
af = pd.read_table('E:/OMI/GRAPH_data/p-af.txt')
aa = pd.read_table('E:/OMI/GRAPH_data/p-aa.txt')
oc = pd.read_table('E:/OMI/GRAPH_data/p-o.txt')
line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)

ame_x = np.array(ame.pku)
ame_y = np.array(ame.average)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(ame_x, ame_y, c='lightsteelblue', alpha=0.8)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.title('Americas', size=15)
plt.ylabel('OMI estimate Kt/yr', size=15)
plt.xlabel('Emission(PKU-FUEL) Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

eu_x = np.array(eu.pku)
eu_y = np.array(eu.average)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(eu_x, eu_y, c='palegreen', alpha=0.8)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.title('Europe', size=15)
plt.ylabel('OMI estimate  Kt/yr', size=15)
plt.xlabel('Emission(PKU-FUEL) Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

af_x = np.array(af.pku)
af_y = np.array(af.average)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(af_x, af_y, c='coral', alpha=0.8)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.title('Africa', size=15)
plt.ylabel('OMI estimate  Kt/yr', size=15)
plt.xlabel('Emission(PKU-FUEL) Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

aa_x = np.array(aa.pku)
aa_y = np.array(aa.average)
plt.xlim(0, 800)
plt.ylim(0, 800)
plt.scatter(aa_x, aa_y, c='deepskyblue', alpha=0.8)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.title('Asia', size=15)
plt.ylabel('OMI estimate  Kt/yr', size=15)
plt.xlabel('Emission(PKU-FUEL) Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

oc_x = np.array(oc.pku)
oc_y = np.array(oc.average)
plt.xlim(0, 120)
plt.ylim(0, 120)
plt.scatter(oc_x, oc_y, c='pink', alpha=0.8)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.title('Oceania', size=15)
plt.ylabel('OMI estimate  Kt/yr', size=15)
plt.xlabel('Emission(PKU-FUEL) Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

plt.show()

