import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


data_address = 'E:/ModisFire/GRAPH_DATA/emission_trend.txt'
file = pd.read_table(data_address)
year = np.array(file.year)
pku = np.array(file.pku)
modis = np.array(file.modis)
ca_pku = np.array(file.ca_pku)
ca_modis = np.array(file.ca_modis)
eu_pku = np.array(file.eu_pku)
eu_modis = np.array(file.eu_modis)
ru_pku = np.array(file.ru_pku)
ru_modis = np.array(file.ru_modis)

plt.figure(figsize=(18, 14))
plt.plot(year, pku/1000, c='red', alpha=5, linewidth=2)
plt.plot(year, modis/1000, c='purple', alpha=5, linewidth=2)
plt.fill_between(year, pku/1000-(pku/1000).std(), pku/1000+(pku/1000).std(), color='sandybrown',alpha=0.5)
plt.fill_between(year, modis/1000-(modis/1000).std(), modis/1000+(modis/1000).std(), color='dodgerblue', alpha=0.5)
plt.xlabel('Year', size=55)
plt.ylabel('BaP(Tons/yr)', size=55)
plt.yticks(fontproperties='Times New Roman', size=45)
plt.xticks(fontproperties='Times New Roman', size=45)
plt.title('Northern boreal forest', size=55)
plt.legend(('PKU', 'This study'), fontsize=40)
plt.savefig('E:/ModisFire/Graph/raw/PAHs emission/figure1.jpeg', format='jpeg', dpi=300)

plt.figure(figsize=(18, 14))
plt.plot(year, ca_pku/1000, c='red', alpha=5, linewidth=2)
plt.plot(year, ca_modis/1000, c='purple', alpha=5, linewidth=2)
plt.fill_between(year, ca_pku/1000-(ca_pku/1000).std(), ca_pku/1000+(ca_pku/1000).std(), color='sandybrown',alpha=0.5)
plt.fill_between(year, ca_modis/1000-(ca_modis/1000).std(), ca_modis/1000+(ca_modis/1000).std(), color='dodgerblue', alpha=0.5)
plt.xlabel('Year', size=50)
plt.ylabel('BaP(Tons/yr)', size=50)
plt.yticks(fontproperties='Times New Roman', size=45)
plt.xticks(fontproperties='Times New Roman', size=45)
plt.title('Canadian boreal forest', size=50)
plt.legend(('PKU', 'This study'), fontsize=40)
plt.savefig('E:/ModisFire/Graph/raw/PAHs emission/figure2.jpeg', format='jpeg', dpi=300)

plt.figure(figsize=(18, 14))
plt.plot(year, eu_pku/1000, c='red', alpha=5, linewidth=2)
plt.plot(year, eu_modis/1000, c='purple', alpha=5, linewidth=2)
plt.fill_between(year, eu_pku/1000-(eu_pku/1000).std(), eu_pku/1000+(eu_pku/1000).std(), color='sandybrown',alpha=0.5)
plt.fill_between(year, eu_modis/1000-(eu_modis/1000).std(), eu_modis/1000+(eu_modis/1000).std(), color='dodgerblue', alpha=0.5)
plt.xlabel('Year', size=50)
plt.ylabel('BaP(Tons/yr)', size=50)
plt.yticks(fontproperties='Times New Roman', size=45)
plt.xticks(fontproperties='Times New Roman', size=45)
plt.title('European boreal forest', size=50)
plt.legend(('PKU', 'This study'), fontsize=40)
plt.savefig('E:/ModisFire/Graph/raw/PAHs emission/figure3.jpeg', format='jpeg', dpi=300)

plt.figure(figsize=(18, 14))
plt.plot(year, ru_pku/1000, c='red', alpha=5, linewidth=2)
plt.plot(year, ru_modis/1000, c='purple', alpha=5, linewidth=2)
plt.fill_between(year, ru_pku/1000-(ru_pku/1000).std(), ru_pku/1000+(ru_pku/1000).std(), color='sandybrown',alpha=0.5)
plt.fill_between(year, ru_modis/1000-(ru_modis/1000).std(), ru_modis/1000+(ru_modis/1000).std(), color='dodgerblue', alpha=0.5)
plt.xlabel('Year', size=50)
plt.ylabel('BaP(Tons/yr)', size=50)
plt.yticks(fontproperties='Times New Roman', size=45)
plt.xticks(fontproperties='Times New Roman', size=45)
plt.title('Russian boreal forest', size=50)
plt.legend(('PKU', 'This study'), fontsize=40)
plt.savefig('E:/ModisFire/Graph/raw/PAHs emission/figure4.jpeg', format='jpeg', dpi=300)