import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


pku = pd.read_table('E:/OMI/GRAPH_data/PKU2.txt')
edgar = pd.read_table('E:/OMI/GRAPH_data/EDGAR2.txt')
ceds = pd.read_table('E:/OMI/GRAPH_data/CEDS2.txt')
eclipse = pd.read_table('E:/OMI/GRAPH_data/ECLIPSE2.txt')
omi_htap = pd.read_table('E:/OMI/GRAPH_data/OMI-HTAP.txt')
plt.rcParams['savefig.dpi'] = 800

plt.subplot(3, 2, 1)
year = np.array(pku.year)
emi = np.array(pku.americas)
plt.plot(year, emi, c='red', alpha=0.5)
year = np.array(edgar.year)
emi = np.array(edgar.americas)
# plt.plot(year, emi, c='blue', alpha=0.5)
year = np.array(ceds.year)
emi = np.array(ceds.americas)
plt.plot(year, emi, c='purple', alpha=0.5)
year = np.array(omi_htap.year)
emi = np.array(omi_htap.americas)
plt.plot(year, emi, c='orange')
year = np.array(eclipse.year)
emi = np.array(eclipse.americas)
# plt.plot(year, emi, c='green', alpha=0.5)
plt.ylabel('Emission(Kt/yr)', fontsize=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.grid(True)

plt.subplot(3,2,2)
year = np.array(pku.year)
emi = np.array(pku.africa)
plt.plot(year, emi, c='red', alpha=0.5)
year = np.array(edgar.year)
emi = np.array(edgar.africa)
# plt.plot(year, emi, c='blue', alpha=0.5)
year = np.array(ceds.year)
emi = np.array(ceds.africa)
plt.plot(year, emi, c='purple', alpha=0.5)
year = np.array(omi_htap.year)
emi = np.array(omi_htap.africa)
plt.plot(year, emi, c='orange')
year = np.array(eclipse.year)
emi = np.array(eclipse.africa)
# plt.plot(year, emi, c='green', alpha=0.5)
plt.ylabel('Emission(Kt/yr)', fontsize=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.grid(True)

plt.subplot(3,2,3)
year = np.array(pku.year)
emi = np.array(pku.europe)
plt.plot(year, emi, c='red', alpha=0.5, label='PKU-FUEL')
year = np.array(edgar.year)
emi = np.array(edgar.europe)
# plt.plot(year, emi, c='blue', alpha=0.5, label='EDGAR')
year = np.array(ceds.year)
emi = np.array(ceds.europe)
plt.plot(year, emi, c='purple', alpha=0.5, label='CEDS')
year = np.array(omi_htap.year)
emi = np.array(omi_htap.europe)
plt.plot(year, emi, c='orange', label='OMI-HTAP')
year = np.array(eclipse.year)
emi = np.array(eclipse.europe)
# plt.plot(year, emi, c='green', alpha=0.5, label='ECLIPSE')
plt.ylabel('Emission(Kt/yr)', fontsize=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.grid(True)

plt.subplot(3,2,4)
year = np.array(pku.year)
emi = np.array(pku.asia)
plt.plot(year, emi, c='red', alpha=0.5)
year = np.array(edgar.year)
emi = np.array(edgar.asia)
# plt.plot(year, emi, c='blue', alpha=0.5)
year = np.array(ceds.year)
emi = np.array(ceds.asia)
plt.plot(year, emi, c='purple', alpha=0.5)
year = np.array(omi_htap.year)
emi = np.array(omi_htap.asia)
plt.plot(year, emi, c='orange')
year = np.array(eclipse.year)
emi = np.array(eclipse.asia)
# plt.plot(year, emi, c='green', alpha=0.5)
plt.xlabel('Year')
plt.ylabel('Emission(Kt/yr)', fontsize=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.grid(True)

plt.subplot(3,2,5)
year = np.array(pku.year)
emi = np.array(pku.oceania)
plt.plot(year, emi, c='red', alpha=0.5)
year = np.array(edgar.year)
emi = np.array(edgar.oceania)
# plt.plot(year, emi, c='blue', alpha=0.5)
year = np.array(eclipse.year)
emi = np.array(eclipse.oceania)
# plt.plot(year, emi, c='green', alpha=0.5)
year = np.array(omi_htap.year)
emi = np.array(omi_htap.oceania)
plt.plot(year, emi, c='orange')
year = np.array(ceds.year)
emi = np.array(ceds.oceania)
plt.plot(year, emi, c='purple', alpha=0.5)
plt.xlabel('Year')
plt.ylabel('Emission(Kt/yr)', fontsize=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.grid(True)
plt.legend(('PKU-FUEL', 'OMI-HTAP', 'CEDS', ), shadow=True, loc=(1.5, 0.08), handlelength=1.5, fontsize=16)
plt.show()

year = np.array(pku.year)
emi = np.array(pku.china)
plt.plot(year, emi, c='red', alpha=0.5)
year = np.array(edgar.year)
emi = np.array(edgar.china)
plt.plot(year, emi, c='blue', alpha=0.5)
year = np.array(eclipse.year)
emi = np.array(eclipse.china)
plt.plot(year, emi, c='green', alpha=0.5)
year = np.array(omi_htap.year)
emi = np.array(omi_htap.china)
plt.plot(year, emi, c='orange')
year = np.array(ceds.year)
emi = np.array(ceds.china)
plt.plot(year, emi, c='purple', alpha=0.5)
plt.xlabel('Year')
plt.ylabel('Emission(Kt/yr)', fontsize=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.grid(True)
plt.legend(('PKU-FUEL', 'EDGAR', 'ECLIPSE', 'OMI-HTAP', 'CEDS', ), shadow=True, loc=(1.5, 0.08), handlelength=1.5,
           fontsize=16)
plt.show()