import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


data = pd.read_table('E:/OMI/GRAPH_data/usepa.txt')
pku = np.array(data.pku)
edgar = np.array(data.edgar)
ceds = np.array(data.ceds)
eclipse = np.array(data.eclipse)
omi = np.array(data.omi)
omi_htap = np.array(data.htap)
usepa = np.array(data.usepa)

line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(usepa, edgar, c='blue', alpha=0.5)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.ylabel('Emission(EDGAR) Kt/yr', size=15)
plt.xlabel('US EPA monitor Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(usepa, ceds, c='purple', alpha=0.5)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.ylabel('Emission(CEDS) Kt/yr', size=15)
plt.xlabel('US EPA monitor Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(usepa, eclipse, c='green', alpha=0.5)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.ylabel('Emission(ECLIPSE) Kt/yr', size=15)
plt.xlabel('US EPA monitor Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(usepa, pku, c='red', alpha=0.5)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.ylabel('Emission(PKU-FUEL) Kt/yr', size=15)
plt.xlabel('US EPA monitor Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(usepa, omi, c='orange', alpha=0.5)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.ylabel('OMI estimate Kt/yr', size=15)
plt.xlabel('US EPA monitor Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()

line_x = np.arange(0, 1000, 10)
line_y = np.arange(0, 1000, 10)
plt.xlim(0, 300)
plt.ylim(0, 300)
plt.scatter(usepa, omi_htap, c='gold', alpha=0.9)
plt.plot(line_x, line_y, c='black', linewidth=0.5)
plt.ylabel('Emission(OMI-HTAP) Kt/yr', size=15)
plt.xlabel('US EPA monitor Kt/yr', size=15)
plt.yticks(fontproperties='Times New Roman', size=15)
plt.xticks(fontproperties='Times New Roman', size=15)
plt.show()
